const accountsConstants = {
  REQUEST_ACCOUNTS_REQUEST: "REQUEST_ACCOUNTS_REQUEST",
  REQUEST_ACCOUNTS_GET: "REQUEST_ACCOUNTS_GET",
  REQUEST_ACCOUNTS_ERROR: "REQUEST_ACCOUNTS_ERROR",
};
export default accountsConstants;
