const accountsConstants = {
  REQUEST_ACCOUNTS_REQUEST: "REQUEST_ACCOUNTS_REQUEST",
  REQUEST_ACCOUNTS_GET: "REQUEST_ACCOUNTS_GET",
  REQUEST_ACCOUNTS_ERROR: "REQUEST_ACCOUNTS_ERROR",
  REQUEST_RATE_REQUEST: "REQUEST_RATE_REQUEST",
  REQUEST_RATE_GET: "REQUEST_RATE_GET",
  REQUEST_RATE_ERROR: "REQUEST_RATE_ERROR",
};
export default accountsConstants;
